//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:26 PM EDT
//
package ca.savi.horse.model.hardware;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="verbose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "resourceListRequest")
public class ResourceListRequest {
  @XmlAttribute(name = "verbose")
  protected Boolean verbose;

  /**
   * Gets the value of the verbose property.
   * @return possible object is {@link Boolean }
   */
  public boolean isVerbose() {
    if (verbose == null) {
      return false;
    } else {
      return verbose;
    }
  }

  /**
   * Sets the value of the verbose property.
   * @param value allowed object is {@link Boolean }
   */
  public void setVerbose(Boolean value) {
    this.verbose = value;
  }
}
