//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:26 PM EDT
//
package ca.savi.horse.model.hardware;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MAC" maxOccurs="4" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vlanID" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "mac" })
@XmlRootElement(name = "setResourceParametersRequest")
public class SetResourceParametersRequest {
  @XmlElement(name = "MAC")
  protected List<SetResourceParametersRequest.MAC> mac;
  @XmlAttribute(name = "uuid")
  protected String uuid;
  @XmlAttribute(name = "vlanID")
  @XmlSchemaType(name = "unsignedShort")
  protected Integer vlanID;
  @XmlAttribute(name = "IP")
  protected String ip;

  /**
   * Gets the value of the mac property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the mac property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getMAC().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link SetResourceParametersRequest.MAC }
   */
  public List<SetResourceParametersRequest.MAC> getMAC() {
    if (mac == null) {
      mac = new ArrayList<SetResourceParametersRequest.MAC>();
    }
    return this.mac;
  }

  /**
   * Gets the value of the uuid property.
   * @return possible object is {@link String }
   */
  public String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the uuid property.
   * @param value allowed object is {@link String }
   */
  public void setUuid(String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the vlanID property.
   * @return possible object is {@link Integer }
   */
  public Integer getVlanID() {
    return vlanID;
  }

  /**
   * Sets the value of the vlanID property.
   * @param value allowed object is {@link Integer }
   */
  public void setVlanID(Integer value) {
    this.vlanID = value;
  }

  /**
   * Gets the value of the ip property.
   * @return possible object is {@link String }
   */
  public String getIP() {
    return ip;
  }

  /**
   * Sets the value of the ip property.
   * @param value allowed object is {@link String }
   */
  public void setIP(String value) {
    this.ip = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
   *         &lt;element name="Addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "index", "addr" })
  public static class MAC {
    protected int index;
    @XmlElement(name = "Addr", required = true)
    protected String addr;

    /**
     * Gets the value of the index property.
     */
    public int getIndex() {
      return index;
    }

    /**
     * Sets the value of the index property.
     */
    public void setIndex(int value) {
      this.index = value;
    }

    /**
     * Gets the value of the addr property.
     * @return possible object is {@link String }
     */
    public String getAddr() {
      return addr;
    }

    /**
     * Sets the value of the addr property.
     * @param value allowed object is {@link String }
     */
    public void setAddr(String value) {
      this.addr = value;
    }
  }
}
