//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:27 PM EDT
//
package ca.savi.horse.model.hardwareprocess;

import ca.savi.horse.model.Hwnode;
import ca.savi.horse.model.Icnode;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hwnode" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                 &lt;attribute name="inUse" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="icnode" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                 &lt;attribute name="linkLeft" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="linkRight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="LRWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                 &lt;attribute name="RLWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                 &lt;attribute name="inUse" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="verbose" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="current" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="maximum" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "hwnode", "icnode" })
@XmlRootElement(name = "resourceListResponse")
public class ResourceListResponse {
  protected List<Hwnode> hwnode;
  protected List<Icnode> icnode;
  @XmlAttribute(name = "verbose")
  protected Boolean verbose;
  @XmlAttribute(name = "current")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger current;
  @XmlAttribute(name = "maximum")
  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger maximum;

  /**
   * Gets the value of the hwnode property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the hwnode property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getHwnode().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ResourceListResponse.Hwnode }
   */
  public List<Hwnode> getHwnode() {
    if (hwnode == null) {
      hwnode = new ArrayList<Hwnode>();
    }
    return this.hwnode;
  }

  /**
   * Gets the value of the icnode property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the icnode property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getIcnode().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ResourceListResponse.Icnode }
   */
  public List<Icnode> getIcnode() {
    if (icnode == null) {
      icnode = new ArrayList<Icnode>();
    }
    return this.icnode;
  }

  /**
   * Gets the value of the verbose property.
   * @return possible object is {@link Boolean }
   */
  public Boolean isVerbose() {
    return verbose;
  }

  /**
   * Sets the value of the verbose property.
   * @param value allowed object is {@link Boolean }
   */
  public void setVerbose(Boolean value) {
    this.verbose = value;
  }

  /**
   * Gets the value of the current property.
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getCurrent() {
    return current;
  }

  /**
   * Sets the value of the current property.
   * @param value allowed object is {@link BigInteger }
   */
  public void setCurrent(BigInteger value) {
    this.current = value;
  }

  /**
   * Gets the value of the maximum property.
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMaximum() {
    return maximum;
  }

  /**
   * Sets the value of the maximum property.
   * @param value allowed object is {@link BigInteger }
   */
  public void setMaximum(BigInteger value) {
    this.maximum = value;
  }
  /**
   * <p>
   * Java class for anonymous complex type.
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
   *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
   *       &lt;attribute name="inUse" type="{http://www.w3.org/2001/XMLSchema}boolean" />
   *       &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  /**
   * <p>
   * Java class for anonymous complex type.
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
   *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
   *       &lt;attribute name="linkLeft" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="linkRight" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="LRWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
   *       &lt;attribute name="RLWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
   *       &lt;attribute name="inUse" type="{http://www.w3.org/2001/XMLSchema}boolean" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
}
