//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:27 PM EDT
//
package ca.savi.horse.model.hardwareprocess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vlanID" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "setResourceParametersRequest")
public class SetResourceParametersRequest {
  @XmlAttribute(name = "uuid")
  protected String uuid;
  @XmlAttribute(name = "vlanID")
  @XmlSchemaType(name = "unsignedShort")
  protected Integer vlanID;
  @XmlAttribute(name = "IP")
  protected String ip;

  /**
   * Gets the value of the uuid property.
   * @return possible object is {@link String }
   */
  public String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the uuid property.
   * @param value allowed object is {@link String }
   */
  public void setUuid(String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the vlanID property.
   * @return possible object is {@link Integer }
   */
  public Integer getVlanID() {
    return vlanID;
  }

  /**
   * Sets the value of the vlanID property.
   * @param value allowed object is {@link Integer }
   */
  public void setVlanID(Integer value) {
    this.vlanID = value;
  }

  /**
   * Gets the value of the ip property.
   * @return possible object is {@link String }
   */
  public String getIP() {
    return ip;
  }

  /**
   * Sets the value of the ip property.
   * @param value allowed object is {@link String }
   */
  public void setIP(String value) {
    this.ip = value;
  }
}
