package ca.savi.cobra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import ca.savi.cobra.model.AddUUIDToFabricRequest;
import ca.savi.cobra.model.AddUUIDToFabricResponse;
import ca.savi.cobra.model.AddVlanToPortRequest;
import ca.savi.cobra.model.AddVlanToPortResponse;
import ca.savi.cobra.model.ClearLocalIfEmptyRequest;
import ca.savi.cobra.model.ClearLocalIfEmptyResponse;
import ca.savi.cobra.model.ClearUUIDRequest;
import ca.savi.cobra.model.ClearUUIDResponse;
import ca.savi.cobra.model.CreateLocalTagRequest;
import ca.savi.cobra.model.CreateLocalTagResponse;
import ca.savi.cobra.model.DescribeFabricRequest;
import ca.savi.cobra.model.DescribeFabricResponse;
import ca.savi.cobra.model.GetIPAddressRequest;
import ca.savi.cobra.model.GetIPAddressResponse;
import ca.savi.cobra.model.GetInternalIPRequest;
import ca.savi.cobra.model.GetInternalIPResponse;
import ca.savi.cobra.model.GetMacAddressRequest;
import ca.savi.cobra.model.GetMacAddressResponse;
import ca.savi.cobra.model.GetNetworkProtocolRequest;
import ca.savi.cobra.model.GetNetworkProtocolResponse;
import ca.savi.cobra.model.GetVlansRequest;
import ca.savi.cobra.model.GetVlansResponse;
import ca.savi.cobra.model.InitializeResponse;
import ca.savi.cobra.model.ObjectFactory;
import ca.savi.cobra.model.ReleaseIPAddressRequest;
import ca.savi.cobra.model.ReleaseIPAddressResponse;
import ca.savi.cobra.model.RemoveMacRestrictionRequest;
import ca.savi.cobra.model.RemoveMacRestrictionResponse;
import ca.savi.cobra.model.RemoveUUIDFromFabricRequest;
import ca.savi.cobra.model.RemoveUUIDFromFabricResponse;
import ca.savi.cobra.model.RemoveVlanFromPortRequest;
import ca.savi.cobra.model.RemoveVlanFromPortResponse;
import ca.savi.cobra.model.ResetResponse;
import ca.savi.cobra.model.RetrieveFabricDescriptionResponse;
import ca.savi.cobra.model.SetMacAddressRequest;
import ca.savi.cobra.model.SetMacAddressResponse;
import ca.savi.cobra.model.TerminateResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI
 * 2.1.3.3-hudson-757-SNAPSHOT Generated source version: 2.1
 */
@WebService(name = "AORFabricPortType", targetNamespace = "fabric.WSDL.AOR")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface AORFabricPortType {
  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.InitializeResponse
   */
  @WebMethod
  @WebResult(name = "initializeResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public InitializeResponse init(@WebParam(name = "initializeRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") Object m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.TerminateResponse
   */
  @WebMethod
  @WebResult(name = "terminateResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public TerminateResponse term(@WebParam(name = "terminateRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") Object m);

  /**
   * @param m
   * @return returns ca.savinetwork.testbed.aorFabricWebService.ResetResponse
   */
  @WebMethod
  @WebResult(name = "resetResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public ResetResponse reset(@WebParam(name = "resetRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") Object m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.AddVlanToPortResponse
   */
  @WebMethod
  @WebResult(name = "addVlanToPortResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public AddVlanToPortResponse addVlanToPort(@WebParam(
      name = "addVlanToPortRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") AddVlanToPortRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.RemoveVlanFromPortResponse
   */
  @WebMethod
  @WebResult(name = "removeVlanFromPortResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public RemoveVlanFromPortResponse removeVlanFromPort(@WebParam(
      name = "removeVlanFromPortRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") RemoveVlanFromPortRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.ClearUUIDResponse
   */
  @WebMethod
  @WebResult(name = "clearUUIDResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public ClearUUIDResponse clearUUID(@WebParam(name = "clearUUIDRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") ClearUUIDRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.DescribeFabricResponse
   */
  @WebMethod
  @WebResult(name = "describeFabricResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public DescribeFabricResponse describeFabric(@WebParam(
      name = "describeFabricRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") DescribeFabricRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.AddUUIDToFabricResponse
   */
  @WebMethod
  @WebResult(name = "addUUIDToFabricResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public AddUUIDToFabricResponse addUUIDToFabric(@WebParam(
      name = "addUUIDToFabricRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") AddUUIDToFabricRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.RemoveUUIDFromFabricResponse
   */
  @WebMethod
  @WebResult(name = "removeUUIDFromFabricResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public RemoveUUIDFromFabricResponse removeUUIDFromFabric(@WebParam(
      name = "removeUUIDFromFabricRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") RemoveUUIDFromFabricRequest m);

  /**
   * @param m
   * @return returns ca.savinetwork.testbed.aorFabricWebService.
   *         RetrieveFabricDescriptionResponse
   */
  @WebMethod
  @WebResult(name = "retrieveFabricDescriptionResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public RetrieveFabricDescriptionResponse retrieveFabricDescription(@WebParam(
      name = "retrieveFabricDescriptionRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") Object m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.GetIPAddressResponse
   */
  @WebMethod
  @WebResult(name = "getIPAddressResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public GetIPAddressResponse getIPAddress(@WebParam(
      name = "getIPAddressRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") GetIPAddressRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.ReleaseIPAddressResponse
   */
  @WebMethod
  @WebResult(name = "releaseIPAddressResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public ReleaseIPAddressResponse releaseIPAddress(@WebParam(
      name = "releaseIPAddressRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") ReleaseIPAddressRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.CreateLocalTagResponse
   */
  @WebMethod
  @WebResult(name = "createLocalTagResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public CreateLocalTagResponse createLocalTag(@WebParam(
      name = "createLocalTagRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") CreateLocalTagRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.GetNetworkProtocolResponse
   */
  @WebMethod
  @WebResult(name = "getNetworkProtocolResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public GetNetworkProtocolResponse getNetworkProtocol(@WebParam(
      name = "getNetworkProtocolRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") GetNetworkProtocolRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.ClearLocalIfEmptyResponse
   */
  @WebMethod
  @WebResult(name = "clearLocalIfEmptyResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public ClearLocalIfEmptyResponse clearLocalIfEmpty(@WebParam(
      name = "clearLocalIfEmptyRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") ClearLocalIfEmptyRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.SetMacAddressResponse
   */
  @WebMethod
  @WebResult(name = "setMacAddressResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public SetMacAddressResponse setMacAddress(@WebParam(
      name = "setMacAddressRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") SetMacAddressRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.RemoveMacRestrictionResponse
   */
  @WebMethod
  @WebResult(name = "removeMacRestrictionResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public RemoveMacRestrictionResponse removeMacRestriction(@WebParam(
      name = "removeMacRestrictionRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") RemoveMacRestrictionRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.GetMacAddressResponse
   */
  @WebMethod
  @WebResult(name = "getMacAddressResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public GetMacAddressResponse getMacAddress(@WebParam(
      name = "getMacAddressRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") GetMacAddressRequest m);

  /**
   * @param m
   * @return returns ca.savinetwork.testbed.aorFabricWebService.GetVlansResponse
   */
  @WebMethod
  @WebResult(name = "getVlansResponse", targetNamespace = "fabric.XSD.AOR",
      partName = "m")
  public GetVlansResponse getUUIDVlans(@WebParam(name = "getVlansRequest",
      targetNamespace = "fabric.XSD.AOR", partName = "m") GetVlansRequest m);

  /**
   * @param m
   * @return returns
   *         ca.savinetwork.testbed.aorFabricWebService.GetInternalIPResponse
   */
  @WebMethod
  @WebResult(name = "getInternalIPResponse",
      targetNamespace = "fabric.XSD.AOR", partName = "m")
  public GetInternalIPResponse getInternalIP(@WebParam(
      name = "getInternalIPRequest", targetNamespace = "fabric.XSD.AOR",
      partName = "m") GetInternalIPRequest m);
}
