//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:31 PM EDT
//
package ca.savi.horse.model.hwparams;

import javax.xml.bind.annotation.XmlRegistry;

import ca.savi.horse.model.FPGA;
import ca.savi.horse.model.Hwnode;
import ca.savi.horse.model.Icnode;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * ca.savinetwork.testbed.type.aorhwparamsschema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package:
   * ca.savinetwork.testbed.type.aorhwparamsschema
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link AddVlanRequestParams }
   */
  public AddVlanRequestParams createAddVlanRequestParams() {
    return new AddVlanRequestParams();
  }

  /**
   * Create an instance of {@link ListResponseParams.Hwnode }
   */
  public Hwnode createListResponseParamsHwnode() {
    return new Hwnode();
  }

  /**
   * Create an instance of {@link SetParamRequestParams }
   */
  public SetParamRequestParams createSetParamRequestParams() {
    return new SetParamRequestParams();
  }

  /**
   * Create an instance of {@link StatusRequestParams }
   */
  public StatusRequestParams createStatusRequestParams() {
    return new StatusRequestParams();
  }

  /**
   * Create an instance of {@link GenericOpResponseParams }
   */
  public GenericOpResponseParams createGenericOpResponseParams() {
    return new GenericOpResponseParams();
  }

  /**
   * Create an instance of {@link TerminateRequestParams }
   */
  public TerminateRequestParams createTerminateRequestParams() {
    return new TerminateRequestParams();
  }

  /**
   * Create an instance of {@link TerminateResponseParams }
   */
  public TerminateResponseParams createTerminateResponseParams() {
    return new TerminateResponseParams();
  }

  /**
   * Create an instance of {@link ListResponseParams }
   */
  public ListResponseParams createListResponseParams() {
    return new ListResponseParams();
  }

  /**
   * Create an instance of {@link GetResponseParams.FPGA }
   */
  public FPGA createGetResponseParamsFPGA() {
    return new FPGA();
  }

  /**
   * Create an instance of {@link ListResponseParams.Icnode }
   */
  public Icnode createListResponseParamsIcnode() {
    return new Icnode();
  }

  /**
   * Create an instance of {@link InitRequestParams }
   */
  public InitRequestParams createInitRequestParams() {
    return new InitRequestParams();
  }

  /**
   * Create an instance of {@link RemoveVlanRequestParams }
   */
  public RemoveVlanRequestParams createRemoveVlanRequestParams() {
    return new RemoveVlanRequestParams();
  }

  /**
   * Create an instance of {@link AddVlanResponseParams }
   */
  public AddVlanResponseParams createAddVlanResponseParams() {
    return new AddVlanResponseParams();
  }

  /**
   * Create an instance of {@link GenericOpRequestParams }
   */
  public GenericOpRequestParams createGenericOpRequestParams() {
    return new GenericOpRequestParams();
  }

  /**
   * Create an instance of {@link FPGA }
   */
  public FPGA createGetRequestParamsFPGA() {
    return new FPGA();
  }

  /**
   * Create an instance of {@link ListRequestParams }
   */
  public ListRequestParams createListRequestParams() {
    return new ListRequestParams();
  }

  /**
   * Create an instance of {@link GetResponseParams }
   */
  public GetResponseParams createGetResponseParams() {
    return new GetResponseParams();
  }

  /**
   * Create an instance of {@link RemoveVlanResponseParams }
   */
  public RemoveVlanResponseParams createRemoveVlanResponseParams() {
    return new RemoveVlanResponseParams();
  }

  /**
   * Create an instance of {@link StatusResponseParams }
   */
  public StatusResponseParams createStatusResponseParams() {
    return new StatusResponseParams();
  }

  /**
   * Create an instance of {@link GetRequestParams }
   */
  public GetRequestParams createGetRequestParams() {
    return new GetRequestParams();
  }

  /**
   * Create an instance of {@link SetParamResponseParams }
   */
  public SetParamResponseParams createSetParamResponseParams() {
    return new SetParamResponseParams();
  }

  /**
   * Create an instance of {@link ResetResponseParams }
   */
  public ResetResponseParams createResetResponseParams() {
    return new ResetResponseParams();
  }

  /**
   * Create an instance of {@link ReleaseRequestParams }
   */
  public ReleaseRequestParams createReleaseRequestParams() {
    return new ReleaseRequestParams();
  }

  /**
   * Create an instance of {@link InitResponseParams }
   */
  public InitResponseParams createInitResponseParams() {
    return new InitResponseParams();
  }

  /**
   * Create an instance of {@link ReleaseResponseParams }
   */
  public ReleaseResponseParams createReleaseResponseParams() {
    return new ReleaseResponseParams();
  }

  /**
   * Create an instance of {@link ResetRequestParams }
   */
  public ResetRequestParams createResetRequestParams() {
    return new ResetRequestParams();
  }
}
