//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:32 PM EDT
//
package ca.savi.horse.model.hwunmarshaller;

import ca.savi.horse.model.FPGA;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * ca.savinetwork.testbed.type.hwUnmarshallerschema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
  private final static QName _UnmarshalReleaseRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalReleaseRequestParams-Response");
  private final static QName _UnmarshalResetRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalResetRequestParams-Response");
  private final static QName _UnmarshalTerminateRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalTerminateRequestParams-Response");
  private final static QName _UnmarshalInitRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalInitRequestParams-Response");
  private final static QName _UnmarshalRemoveVlanRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalRemoveVlanRequestParams-Response");
  private final static QName _UnmarshalStatusRequestParamsResponse_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareUnmarshaller",
          "UnmarshalStatusRequestParams-Response");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package:
   * ca.savinetwork.testbed.type.hwUnmarshallerschema
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link UnmarshalListRequestParamsResponse }
   */
  public UnmarshalListRequestParamsResponse
      createUnmarshalListRequestParamsResponse() {
    return new UnmarshalListRequestParamsResponse();
  }

  /**
   * Create an instance of {@link UnmarshalInitRequestParamsRequest }
   */
  public UnmarshalInitRequestParamsRequest
      createUnmarshalInitRequestParamsRequest() {
    return new UnmarshalInitRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalTerminateRequestParamsRequest }
   */
  public UnmarshalTerminateRequestParamsRequest
      createUnmarshalTerminateRequestParamsRequest() {
    return new UnmarshalTerminateRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalGetRequestParamsResponse }
   */
  public UnmarshalGetRequestParamsResponse
      createUnmarshalGetRequestParamsResponse() {
    return new UnmarshalGetRequestParamsResponse();
  }

  /**
   * Create an instance of
   * {@link UnmarshalGenericOperationRequestParamsResponse }
   */
  public UnmarshalGenericOperationRequestParamsResponse
      createUnmarshalGenericOperationRequestParamsResponse() {
    return new UnmarshalGenericOperationRequestParamsResponse();
  }

  /**
   * Create an instance of {@link UnmarshalAddVlanRequestParamsRequest }
   */
  public UnmarshalAddVlanRequestParamsRequest
      createUnmarshalAddVlanRequestParamsRequest() {
    return new UnmarshalAddVlanRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalRemoveVlanRequestParamsRequest }
   */
  public UnmarshalRemoveVlanRequestParamsRequest
      createUnmarshalRemoveVlanRequestParamsRequest() {
    return new UnmarshalRemoveVlanRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalSetParamRequestParamsRequest }
   */
  public UnmarshalSetParamRequestParamsRequest
      createUnmarshalSetParamRequestParamsRequest() {
    return new UnmarshalSetParamRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalListRequestParamsRequest }
   */
  public UnmarshalListRequestParamsRequest
      createUnmarshalListRequestParamsRequest() {
    return new UnmarshalListRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalAddVlanRequestParamsResponse }
   */
  public UnmarshalAddVlanRequestParamsResponse
      createUnmarshalAddVlanRequestParamsResponse() {
    return new UnmarshalAddVlanRequestParamsResponse();
  }

  /**
   * Create an instance of {@link UnmarshalGenericOperationRequestParamsRequest }
   */
  public UnmarshalGenericOperationRequestParamsRequest
      createUnmarshalGenericOperationRequestParamsRequest() {
    return new UnmarshalGenericOperationRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalResetRequestParamsRequest }
   */
  public UnmarshalResetRequestParamsRequest
      createUnmarshalResetRequestParamsRequest() {
    return new UnmarshalResetRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalGetRequestParamsRequest }
   */
  public UnmarshalGetRequestParamsRequest
      createUnmarshalGetRequestParamsRequest() {
    return new UnmarshalGetRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalReleaseRequestParamsRequest }
   */
  public UnmarshalReleaseRequestParamsRequest
      createUnmarshalReleaseRequestParamsRequest() {
    return new UnmarshalReleaseRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalProgramRequestParamsRequest }
   */
  public UnmarshalProgramRequestParamsRequest
      createUnmarshalProgramRequestParamsRequest() {
    return new UnmarshalProgramRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalProgramRequestParamsResponse }
   */
  public UnmarshalProgramRequestParamsResponse
      createUnmarshalProgramRequestParamsResponse() {
    return new UnmarshalProgramRequestParamsResponse();
  }

  /**
   * Create an instance of {@link UnmarshalGetRequestParamsResponse.FPGA }
   */
  public FPGA createUnmarshalGetRequestParamsResponseFPGA() {
    return new FPGA();
  }

  /**
   * Create an instance of {@link UnmarshalStatusRequestParamsRequest }
   */
  public UnmarshalStatusRequestParamsRequest
      createUnmarshalStatusRequestParamsRequest() {
    return new UnmarshalStatusRequestParamsRequest();
  }

  /**
   * Create an instance of {@link UnmarshalSetParamRequestParamsResponse }
   */
  public UnmarshalSetParamRequestParamsResponse
      createUnmarshalSetParamRequestParamsResponse() {
    return new UnmarshalSetParamRequestParamsResponse();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalReleaseRequestParams-Response")
  public JAXBElement<Object> createUnmarshalReleaseRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(
        _UnmarshalReleaseRequestParamsResponse_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalResetRequestParams-Response")
  public JAXBElement<Object> createUnmarshalResetRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(_UnmarshalResetRequestParamsResponse_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalTerminateRequestParams-Response")
  public JAXBElement<Object> createUnmarshalTerminateRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(
        _UnmarshalTerminateRequestParamsResponse_QNAME, Object.class, null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalInitRequestParams-Response")
  public JAXBElement<Object> createUnmarshalInitRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(_UnmarshalInitRequestParamsResponse_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalRemoveVlanRequestParams-Response")
  public JAXBElement<Object> createUnmarshalRemoveVlanRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(
        _UnmarshalRemoveVlanRequestParamsResponse_QNAME, Object.class, null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareUnmarshaller",
      name = "UnmarshalStatusRequestParams-Response")
  public JAXBElement<Object> createUnmarshalStatusRequestParamsResponse(
      Object value) {
    return new JAXBElement<Object>(_UnmarshalStatusRequestParamsResponse_QNAME,
        Object.class, null, value);
  }
}
