//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:32 PM EDT
//
package ca.savi.horse.model.hwunmarshaller;

import ca.savi.horse.model.FPGA;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FPGA" maxOccurs="4" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LRWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="RLWidth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="rawEthernet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fpga", "uuid", "lrWidth", "rlWidth",
    "rawEthernet" })
@XmlRootElement(name = "UnmarshalGetRequestParams-Response")
public class UnmarshalGetRequestParamsResponse {
  @XmlElement(name = "FPGA")
  protected List<FPGA> fpga;
  protected String uuid;
  @XmlElement(name = "LRWidth")
  @XmlSchemaType(name = "unsignedShort")
  protected Integer lrWidth;
  @XmlElement(name = "RLWidth")
  @XmlSchemaType(name = "unsignedShort")
  protected Integer rlWidth;
  protected Boolean rawEthernet;

  /**
   * Gets the value of the fpga property.
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the fpga property.
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getFPGA().add(newItem);
   * </pre>
   * <p>
   * Objects of the following type(s) are allowed in the list {@link FPGA }
   */
  public List<FPGA> getFPGA() {
    if (fpga == null) {
      fpga = new ArrayList<FPGA>();
    }
    return this.fpga;
  }

  /**
   * Gets the value of the uuid property.
   * @return possible object is {@link String }
   */
  public String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the uuid property.
   * @param value allowed object is {@link String }
   */
  public void setUuid(String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the lrWidth property.
   * @return possible object is {@link Integer }
   */
  public Integer getLRWidth() {
    return lrWidth;
  }

  /**
   * Sets the value of the lrWidth property.
   * @param value allowed object is {@link Integer }
   */
  public void setLRWidth(Integer value) {
    this.lrWidth = value;
  }

  /**
   * Gets the value of the rlWidth property.
   * @return possible object is {@link Integer }
   */
  public Integer getRLWidth() {
    return rlWidth;
  }

  /**
   * Sets the value of the rlWidth property.
   * @param value allowed object is {@link Integer }
   */
  public void setRLWidth(Integer value) {
    this.rlWidth = value;
  }

  /**
   * Gets the value of the rawEthernet property.
   * @return possible object is {@link Boolean }
   */
  public Boolean isRawEthernet() {
    return rawEthernet;
  }

  /**
   * Sets the value of the rawEthernet property.
   * @param value allowed object is {@link Boolean }
   */
  public void setRawEthernet(Boolean value) {
    this.rawEthernet = value;
  }
  /**
   * <p>
   * Java class for anonymous complex type.
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/>
   *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
}
