//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:31 PM EDT
//
package ca.savi.horse.model.hwmarshaller;

import ca.savi.horse.model.FPGA;
import ca.savi.horse.model.Hwnode;
import ca.savi.horse.model.Icnode;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * ca.savinetwork.testbed.type.hwmarshallerschema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
  private final static QName _MarshalInitResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalInitResponseParams-Request");
  private final static QName _MarshalResetResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalResetResponseParams-Request");
  private final static QName _MarshalReleaseResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalReleaseResponseParams-Request");
  private final static QName _MarshalTerminateResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalTerminateResponseParams-Request");
  private final static QName _MarshalRemoveVlanResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalRemoveVlanResponseParams-Request");
  private final static QName _MarshalAddVlanResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalAddVlanResponseParams-Request");
  private final static QName _MarshalProgramResponseParamsRequest_QNAME =
      new QName("http://xml.netbeans.org/schema/HardwareMarshallerSchema",
          "MarshalProgramResponseParams-Request");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package:
   * ca.savinetwork.testbed.type.hwmarshallerschema
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link MarshalGenericOperationResponseParamsResponse }
   */
  public MarshalGenericOperationResponseParamsResponse
      createMarshalGenericOperationResponseParamsResponse() {
    return new MarshalGenericOperationResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalListResponseParamsRequest.Hwnode }
   */
  public Hwnode createMarshalListResponseParamsRequestHwnode() {
    return new Hwnode();
  }

  /**
   * Create an instance of {@link MarshalTerminateResponseParamsResponse }
   */
  public MarshalTerminateResponseParamsResponse
      createMarshalTerminateResponseParamsResponse() {
    return new MarshalTerminateResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalListResponseParamsResponse }
   */
  public MarshalListResponseParamsResponse
      createMarshalListResponseParamsResponse() {
    return new MarshalListResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalListResponseParamsRequest }
   */
  public MarshalListResponseParamsRequest
      createMarshalListResponseParamsRequest() {
    return new MarshalListResponseParamsRequest();
  }

  /**
   * Create an instance of {@link MarshalAddVlanResponseParamsResponse }
   */
  public MarshalAddVlanResponseParamsResponse
      createMarshalAddVlanResponseParamsResponse() {
    return new MarshalAddVlanResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalReleaseResponseParamsResponse }
   */
  public MarshalReleaseResponseParamsResponse
      createMarshalReleaseResponseParamsResponse() {
    return new MarshalReleaseResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalGetResponseParamsRequest.FPGA }
   */
  public FPGA createMarshalGetResponseParamsRequestFPGA() {
    return new FPGA();
  }

  /**
   * Create an instance of {@link MarshalProgramResponseParamsResponse }
   */
  public MarshalProgramResponseParamsResponse
      createMarshalProgramResponseParamsResponse() {
    return new MarshalProgramResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalInitResponseParamsResponse }
   */
  public MarshalInitResponseParamsResponse
      createMarshalInitResponseParamsResponse() {
    return new MarshalInitResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalRemoveVlanResponseParamsResponse }
   */
  public MarshalRemoveVlanResponseParamsResponse
      createMarshalRemoveVlanResponseParamsResponse() {
    return new MarshalRemoveVlanResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalGetResponseParamsRequest }
   */
  public MarshalGetResponseParamsRequest
      createMarshalGetResponseParamsRequest() {
    return new MarshalGetResponseParamsRequest();
  }

  /**
   * Create an instance of {@link MarshalGetResponseParamsResponse }
   */
  public MarshalGetResponseParamsResponse
      createMarshalGetResponseParamsResponse() {
    return new MarshalGetResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalStatusResponseParamsRequest }
   */
  public MarshalStatusResponseParamsRequest
      createMarshalStatusResponseParamsRequest() {
    return new MarshalStatusResponseParamsRequest();
  }

  /**
   * Create an instance of {@link MarshalGenericOperationResponseParamsRequest }
   */
  public MarshalGenericOperationResponseParamsRequest
      createMarshalGenericOperationResponseParamsRequest() {
    return new MarshalGenericOperationResponseParamsRequest();
  }

  /**
   * Create an instance of {@link MarshalStatusResponseParamsResponse }
   */
  public MarshalStatusResponseParamsResponse
      createMarshalStatusResponseParamsResponse() {
    return new MarshalStatusResponseParamsResponse();
  }

  /**
   * Create an instance of {@link MarshalListResponseParamsRequest.Icnode }
   */
  public Icnode createMarshalListResponseParamsRequestIcnode() {
    return new Icnode();
  }

  /**
   * Create an instance of {@link MarshalResetResponseParamsResponse }
   */
  public MarshalResetResponseParamsResponse
      createMarshalResetResponseParamsResponse() {
    return new MarshalResetResponseParamsResponse();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalInitResponseParams-Request")
  public JAXBElement<Object>
      createMarshalInitResponseParamsRequest(Object value) {
    return new JAXBElement<Object>(_MarshalInitResponseParamsRequest_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalResetResponseParams-Request")
  public JAXBElement<Object> createMarshalResetResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(_MarshalResetResponseParamsRequest_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalReleaseResponseParams-Request")
  public JAXBElement<Object> createMarshalReleaseResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(_MarshalReleaseResponseParamsRequest_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalTerminateResponseParams-Request")
  public JAXBElement<Object> createMarshalTerminateResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(
        _MarshalTerminateResponseParamsRequest_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalRemoveVlanResponseParams-Request")
  public JAXBElement<Object> createMarshalRemoveVlanResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(
        _MarshalRemoveVlanResponseParamsRequest_QNAME, Object.class, null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalAddVlanResponseParams-Request")
  public JAXBElement<Object> createMarshalAddVlanResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(_MarshalAddVlanResponseParamsRequest_QNAME,
        Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
      name = "MarshalProgramResponseParams-Request")
  public JAXBElement<Object> createMarshalProgramResponseParamsRequest(
      Object value) {
    return new JAXBElement<Object>(_MarshalProgramResponseParamsRequest_QNAME,
        Object.class, null, value);
  }
}
