//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.03.19 at 01:54:31 PM EDT
//
@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://xml.netbeans.org/schema/HardwareMarshallerSchema",
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.savi.horse.model.hwmarshaller;

